# Use the official Node.js image
FROM node:20-alpine

# Install rsync and other dependencies using apk (Alpine package manager)
RUN apk add --no-cache rsync

# Set working directory
WORKDIR /usr/src/app

# Copy package files and install dependencies
COPY package.json package-lock.json ./
RUN npm install
RUN mkdir -p /usr/src/cache && cp -r node_modules /usr/src/cache/node_modules

# Copy the rest of the application code
COPY . .

# Expose the port for development
EXPOSE 3000

# Use nodemon for development
CMD ["npx", "nodemon", "src/index.js"]
