services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: inside
      DB_PASS: inside
      DB_NAME: inside
    ports:
      - '3000:3000'
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/usr/src/app

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: inside
      POSTGRES_PASSWORD: inside
      POSTGRES_DB: inside
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U inside -d inside']
      interval: 2s
      timeout: 5s
      retries: 5

volumes:
  db-data:
